name: test

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: cache yarn.lock
        uses: actions/cache@v1
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: hack for singe file
        run: |
          if [ ! -d "package-temp-dir" ]; then
            mkdir package-temp-dir
          fi
          cp yarn.lock package-temp-dir

      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/yarn.lock') }}

      - name: install
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: yarn

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: restore cache from yarn.lock
        uses: actions/cache@v1
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/yarn.lock') }}

      - name: lint
        run: npm run lint
    needs: setup

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: restore cache from yarn.lock
        uses: actions/cache@v1
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/yarn.lock') }}

      - name: test
        run: npm test
    needs: setup
